# Generated by Django 5.0.14 on 2026-01-26 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('grid', 'Grid Power'), ('solar', 'Solar Power'), ('battery', 'Battery Power'), ('generator', 'Generator')], max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity in watts', null=True)),
                ('current_output', models.FloatField(default=0, help_text='Current output in watts')),
                ('priority', models.IntegerField(default=0, help_text='Priority level (higher is better)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('preference_value', models.JSONField(help_text='Preference value in JSON format')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('power_source', 'Power Source Selection'), ('light_dim', 'Light Dimming'), ('load_shift', 'Load Shifting'), ('general', 'General Recommendation')], db_index=True, max_length=30)),
                ('decision', models.JSONField(help_text="The AI's decision in JSON format")),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score (0-1)')),
                ('reasoning', models.TextField(blank=True, help_text='Explanation of the decision')),
                ('applied', models.BooleanField(default=False, help_text='Whether the decision was applied')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['decision_type', '-timestamp'], name='data_pipeli_decisio_bc1673_idx')],
            },
        ),
        migrations.CreateModel(
            name='GridData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('carbon_intensity', 'Grid Carbon Intensity'), ('weather', 'Weather Data'), ('electricity_price', 'Electricity Price')], db_index=True, max_length=30)),
                ('value', models.FloatField(help_text='Primary value (e.g., carbon intensity in gCO2/kWh)')),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=20)),
                ('zone', models.CharField(default='IN-KA', help_text='Grid zone identifier', max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data in JSON format')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['data_type', '-timestamp'], name='data_pipeli_data_ty_894eae_idx'), models.Index(fields=['zone', '-timestamp'], name='data_pipeli_zone_1d53ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('ldr', 'Light Dependent Resistor'), ('current', 'Current Sensor'), ('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor')], db_index=True, max_length=20)),
                ('sensor_id', models.CharField(db_index=True, help_text='Unique identifier for the sensor', max_length=50)),
                ('value', models.FloatField(help_text='Sensor reading value')),
                ('unit', models.CharField(default='raw', help_text='Unit of measurement', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Location of the sensor (e.g., living_room)', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_type', '-timestamp'], name='data_pipeli_sensor__0c6fd6_idx'), models.Index(fields=['sensor_id', '-timestamp'], name='data_pipeli_sensor__2e0976_idx')],
            },
        ),
    ]
