# Generated by Django 5.0.14 on 2026-01-26 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Load identifier (e.g., 'Living Room HVAC')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('hvac', 'HVAC System'), ('lighting', 'Lighting'), ('appliance', 'Appliance'), ('computing', 'Computing'), ('entertainment', 'Entertainment'), ('security', 'Security System'), ('communication', 'Communication'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.IntegerField(choices=[(100, 'Critical'), (75, 'High'), (50, 'Medium'), (25, 'Low')], default=50, help_text='Load priority level')),
                ('rated_power', models.FloatField(help_text='Rated power consumption in watts')),
                ('current_power', models.FloatField(default=0, help_text='Current power consumption in watts')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the load is currently active')),
                ('current_source', models.CharField(blank=True, choices=[('grid', 'Grid Power'), ('solar', 'Solar Power'), ('battery', 'Battery Power'), ('generator', 'Generator')], help_text='Current energy source powering this load', max_length=20, null=True)),
                ('can_defer', models.BooleanField(default=False, help_text='Can this load be deferred to off-peak times?')),
                ('min_runtime', models.IntegerField(default=0, help_text='Minimum continuous runtime in minutes')),
                ('location', models.CharField(blank=True, help_text='Physical location of the load', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this load')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceSwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_source', models.CharField(blank=True, choices=[('grid', 'Grid Power'), ('solar', 'Solar Power'), ('battery', 'Battery Power'), ('generator', 'Generator')], help_text='Previous energy source', max_length=20, null=True)),
                ('to_source', models.CharField(choices=[('grid', 'Grid Power'), ('solar', 'Solar Power'), ('battery', 'Battery Power'), ('generator', 'Generator')], help_text='New energy source', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the switch')),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('ai', 'AI Decision'), ('emergency', 'Emergency')], default='automatic', max_length=20)),
                ('expected_savings', models.FloatField(blank=True, help_text='Expected cost/carbon savings', null=True)),
                ('actual_savings', models.FloatField(blank=True, help_text='Actual savings (filled in later)', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the switch was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error details if switch failed')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_events', to='data_pipeline.load')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['load', '-timestamp'], name='data_pipeli_load_id_ae5f4c_idx'), models.Index(fields=['to_source', '-timestamp'], name='data_pipeli_to_sour_ca371c_idx')],
            },
        ),
    ]
